Repository freeCodeCamp/chinese, pull requests merged in 2019-11, with the labels that each got.

#54 Object Oriented Programming Concepts
  chinese/articles/object-oriented-programming-concepts.md
Labels: Review-in-progress

#114 Async Generators作为状态管理的替代方案
  chinese/articles/async-generators-as-alternative-to-state-management.md
Labels: Review-completed

#44 [Add] 使用 React Hooks 创建可复用的动画组件
  chinese/articles/animating-visibility-with-css-an-example-of-react-hooks.md
Labels: Published

#103 通过构建你自己的 Slack App 来学习 Serverless
  chinese/articles/make-a-serverless-slack-app.md
Labels: Review-awaiting
