Repository freeCodeCamp/chinese, pull requests merged in 2019-12, with the labels that each got.

#121 开源社区贡献指南
  chinese/articles/the-definitive-guide-to-contributing-to-open-source.md
Labels: Review-completed

#64 The Definitive Guide to Contributing to Open Source
  chinese/articles/the-definitive-guide-to-contributing-to-open-source.md
Labels: Translation-in-progress

#104 2019自由职业程序员如何打造个人品牌
  chinese/articles/how-to-brand-yourself-as-a-freelance-developer-in-2019-and-beyond.md
Labels: Review-awaiting

#66 Translate/how to build a json api with python
  chinese/articles/build-a-simple-json-api-in-python.md
Labels: Review-completed

#62 如何使用React Native构建实时todo应用程序
  chinese/articles/how-to-build-a-real-time-todo-app-with-react-native.md
Labels: Review-completed

#152 Web Development in 2020: What You Should Learn
  chinese/articles/web-development-2020.md
Labels: Review-completed
