Repository freeCodeCamp/chinese, pull requests merged in 2020-06, with the labels that each got.

#185 如何用 CSS 绘制甘特图
  chinese/articles/create-gantt-chart-using-css-grid.md
Labels: Review-awaiting

#195 服务生跳出舒适区自学编程，成功挑战人生第一次黑客马拉松
  chinese/articles/how-i-won-the-hackathon.md
Labels: Review-awaiting

#180 使用 GitHub Pages，10 分钟搭建静态网页
  chinese/articles/create-a-free-static-site-with-github-pages-in-10-minutes.md
Labels: Review-completed

#163 你需要知道的 CSS 变量
  chinese/articles/everything-you-need-to-know-about-css-variables.md
Labels: Published

#209 如何使用React.js创建你的个人作品集网页
  chinese/articles/portfolio-app-using-react.md
Labels: Review-awaiting

#208 Translated How to Create a Todo API in Deno and Oak
  chinese/articles/create-a-todo-api-in-deno-written-by-a-guy-coming-from-node.md
  chinese/articles/how-to-use-mysql-with-deno-and-oak.md
Labels: Published

#144 我是如何从全职妈妈开始我的第一份Web开发职位的
  chinese/articles/how-i-went-from-stay-at-home-mum-to-landing-my-first-web-developer-job.md
Labels: Published

#217 Vue.js 项目实践——创建记忆卡牌小游戏
  chinese/articles/how-to-build-a-memory-card-game-with-vuejs.md
Labels: Published
