Repository freeCodeCamp/chinese, pull requests merged in 2020-04, with the labels that each got.

#145 Translate/news tags
  chinese/articles/news-tags.md
Labels: Review-awaiting

#184 掌握这些方法，编程可以更有趣
  chinese/articles/how-to-make-programming-more-exciting-and-funnier.md
Labels: Review-completed

#159 我如何在七个月内成为前端工程师？你也可以做到！
  chinese/articles/# 128 how-i-became-a-web-developer-in-under-7-months-and-how-you-can-too.md
  chinese/articles/how-i-became-a-web-developer-in-under-7-months-and-how-you-can-too.md
Labels: Published

#193 Update the-first-step-towards-learning-to-code.md
  chinese/articles/the-first-step-towards-learning-to-code.md
Labels: Published
