Repository freeCodeCamp/chinese, pull requests merged in 2020-12, with the labels that each got.

#246 #215 前端和后端的区别到底是什么？非程序员也能读懂！
  chinese/articles/front-end-developer-vs-back-end-developer-definition-and-meaning-in-practice.md
Labels: Review-awaiting

#258 没有计算机相关学位，怎么成为软件工程师
  chinese/articles/paths-to-becoming-a-software-engineer.md
Labels: Review-awaiting

#255 Java 数组的打印方式
  chinese/articles/how-to-print-an-array-in-java.md
Labels: Review-awaiting

#263 如何设置 Java Spring Boot JWT 授权和认证
  chinese/articles/how-to-setup-jwt-authorization-and-authentication-in-spring.md
Labels: Review-awaiting

#154 Vue 手册：一份全面的 Vue.js 介绍
  chinese/articles/the-vue-handbook-a-thorough-introduction-to-vue-js.md
Labels: Review-awaiting

#271 feat:JavaScript 字符串反转的三种方式
  .gitignore
  chinese/articles/how-to-reverse-a-string-in-javascript-in-3-different-ways.md
Labels: Review-awaiting

#261 一个月之内参加 60 多场面试，我收获了什么？
  chinese/articles/what-i-learned-from-doing-60-technical-interviews-in-30-days.md
Labels: Published

#290 translate
  chinese/articles/how-i-learned-to-code-without-a-cs-degree-or-bootcamp.md
Labels: Review-completed

#286 什么是自由职业？如何在自己生活的城市获取线上工作机会和客户
  chinese/articles/what-is-freelancing.md
Labels: Review-completed

#298 回顾 50 道问题，击破 Java 面试
  chinese/articles/review-these-50-questions-to-crack-your-java-programming-interview.md
Labels: Review-completed

#305 Git 内部原理图解——对象、分支以及如何从零开始建仓库
  chinese/articles/git-internals-objects-branches-create-repo.md
Labels: Review-awaiting
