Repository freeCodeCamp/chinese, pull requests merged in 2021-04, with the labels that each got.

#411 Linux LS 命令
  chinese/articles/the-linux-ls-command-how-to-list-files-in-a-directory-with-options.md
Labels: Published

#410 Docker 入门教程 - 2021 最新版
  chinese/articles/the-docker-handbook.md
Labels: Published

#369 JavaScript 编程中最常见的 9 个错误（以及解决办法）
  chinese/articles/nine-most-common-mistakes-developers-make-in-javascript.md
Labels: Review-completed

#423 什么是毛玻璃效果（Glassmorphism）？仅使用 HTML 和 CSS 来制作这种效果
  chinese/articles/glassmorphism-design-effect-with-html-css.md
Labels: Review-awaiting

#427 如何成为一名优秀的开源项目负责人——终极指南
  chinese/articles/ultimate-owners-guide-to-open-source.md
Labels: Review-awaiting

#398 阅读 Git 代码，提升你的编程技能
  chinese/articles/boost-programming-skills-read-git-code.md
Labels: Published

#428 JavaScript 函数式编程入门指南
  chinese/articles/functional-programming-in-javascript-for-beginners.md
Labels: Review-awaiting

#425 translation from english to chinese completed
  chinese/articles/what-is-git-learn-git-version-control.md
Labels: Review-awaiting

#346 Newdegen patch 2
  chinese/articles/from-civil-engineer-to-web-developer-with-freecodecamp.md
Labels: Published

#447 docs: translate done - deno-url- shortener
  chinese/articles/build-a-url-shortener-in-deno.md
Labels: Published

#448 docs: translate done - deno-aleph-react
  chinese/articles/build-react-app-using-deno-and-alephjs.md
Labels: Published
