Repository freeCodeCamp/chinese, pull requests merged in 2021-06, with the labels that each got.

#424 Cookies 看这一篇就够了
  chinese/articles/everything-you-need-to-know-about-cookies-for-web-development.md
Labels: Published

#475 写给新人的指南——如何为开源项目做贡献
  chinese/articles/how-to-contribute-to-open-source-projects-beginners-guide.md
Labels: Review-awaiting

#470 Python 代码示例——面向初学者的示例脚本编程教程
  chinese/articles/python-code-examples-sample-script-coding-tutorial-for-beginners.md
Labels: Review-awaiting, Translation-in-progress

#443 我用 Beautiful Soup 创建 Web 爬虫程序，并找到第一份工作
  chinese/articles/how-i-used-a-side-project-to-land-a-job.md
Labels: Published

#279 如何 Git Clone 指定分支
  chinese/articles/git-clone-branch-how-to-clone-a-specific-branch.md
Labels: Review-awaiting

#477 翻译完成
  chinese/articles/5-react-lessons-tutorials-dont-teach.md
Labels: Review-awaiting

#487 JavaScript Async/Await 教程
  chinese/articles/javascript-async-await-tutorial-learn-callbacks-promises-async-await-by-making-icecream.md
Labels: Review-awaiting

#497 什么是软件测试？开发人员在项目中使用的 10 种最常见的测试类型
  chinese/articles/types-of-software-testing.md
Labels: Review-awaiting
