Repository freeCodeCamp/chinese, pull requests merged in 2021-05, with the labels that each got.

#345 自由职业开发者完全指南
  chinese/articles/freelance-web-developer-guide.md
Labels: Published

#337 学习音乐的经历如何帮助我学习编程
  chinese/articles/how-my-musical-training-helped-me-learn-how-to-code.md
Labels: Published, Review-awaiting

#357 我从第一次构建项目中学到了什么
  chinese/articles/what-i-learned-from-building-my-first-solo-project.md
Labels: Published

#293 React.js 入门教程
  chinese/articles/react-beginner-handbook.md
Labels: Translation-in-progress
