Repository freeCodeCamp/chinese, pull requests merged in 2022-10, with the labels that each got.

#852 python编程手册
  chinese/articles/the-python-handbook.md
Labels: Review-awaiting

#965 认证和授权有什么区别
  chinese/articles/whats-the-difference-between-authentication-and-authorisation.md
Labels: Translation-in-progress

#41 [add] 所有开发者都应该知道的基础设计模式
  chinese/articles/the-basic-design-patterns-all-developers-need-to-know.md
Labels: Published

#179 React 使用手册
  chinese/articles/the-react-handbook.md
Labels: Review-in-progress

#325 VS Code snippet 入门指南
  chinese/articles/definitive-guide-to-snippets-visual-studio-code.md
Labels: Review-in-progress

#961 未来的 JavaScript
  chinese/articles/future-of-javascript.md
Labels: Translation-in-progress

#968 如何用 JavaScript 搭建一个模态框
  chinese/articles/how-to-build-a-modal-with-javascript.md
Labels: Translation-in-progress

#945 什么是Web3？解读未来的去中心化网络
  chinese/articles/what-is-web3.md
Labels: Translation-in-progress
