Repository freeCodeCamp/chinese, pull requests merged in 2022-12, with the labels that each got.

#1011 浏览器渲染网页
  chinese/articles/web-page-rendering-on-the-browser-different-methods.md
Labels: Translation-in-progress

#1019 面向初学者的 Linux Shell——解释 Bash、Zsh 和 Fish
  chinese/articles/linux-shells-explained.md
Labels: Translation-in-progress

#96 一些可以提升你编程水平的应用创意想法
  chinese/articles/here-are-some-app-ideas-you-can-build-to-level-up-your-coding-skills.md
Labels: Review-awaiting

#176 Python学习：从小白到大神
  chinese/articles/learning-python-from-zero-to-hero-updated-issue.md
Labels: Review-awaiting

#1009 Express+Node.js手册
  chinese/articles/the-express-handbook.md
Labels: Translation-in-progress

#1025 如何通过Python创建一个Telegram机器人
  chinese/articles/how-to-create-a-telegram-bot-using-python.md
Labels: Published

#1023 更好的React性能——何时使用useCallback和useMemo
  chinese/articles/better-react-performance-usecallback-vs-usememo.md
Labels: Translation-in-progress
