Repository freeCodeCamp/chinese, pull requests merged in 2023-01, with the labels that each got.

#1036 使用 CSS 构建 Figma logo
  chinese/articles/learn-css-by-creating-the-figma-logo-in-pure-css.md
Labels: Published

#1021 开发者为何要写技术文章以及应该如何写作
  chinese/articles/developers-the-why-and-how-to-writing-technical-articles-54e824789ef6.md
Labels: Translation-in-progress

#915 Markdown 手册 —— 如何用 Markdown 语言写文章
  chinese/articles/markdown-cheatsheet.md
Labels: Translation-in-progress

#1048 通过建立CI/CD管道来学习Jenkins
  chinese/articles/learn-jenkins-by-building-a-ci-cd-pipeline.md
Labels: Published

#1050 Learn to code book L1495-L1794
  chinese/articles/learn-to-code-book.md
Labels: Review-completed
