Repository freeCodeCamp/chinese, pull requests merged in 2023-05, with the labels that each got.

#1125 Update how-to-write-a-good-technical-tutorial.md
  chinese/articles/how-to-write-a-good-technical-tutorial.md
Labels: Translation-in-progress

#571 What is a block cipher
  chinese/articles/what-is-a-block-cipher.md
Labels: Review-awaiting

#572 斯科菲尔德定律
  chinese/articles/schofields-laws-of-computing.md
Labels: Review-awaiting

#573 How to perform crud operations using react hooks and axios
  chinese/articles/how-to-perform-crud-operations-using-react.md
Labels: Review-awaiting

#577 What new in react 18
  chinese/articles/whats-new-in-react-18.md
Labels: Review-awaiting

#578 The complete guide to full stack development with supabas
  chinese/articles/the-complete-guide-to-full-stack-development-with-supabas.md
Labels: Review-awaiting

#584 Best practices for react
  chinese/articles/best-practices-for-react.md
Labels: Review-awaiting

#597 Learn web development free full stack developer courses for beginners
  chinese/articles/learn-web-development-free-full-stack-developer-courses-for-beginners.md
Labels: Published
